import { Panel, NumberField, Result, Notice, Plot, Formula } from '../shared';
import { logGamma } from '../math';
import { useToolState } from '../workspace';
import { captured, conclusion } from './common';
import { goodnessOfFit, independence, mergeAdjacent, serializeGroups } from './chi-square';
import { initialChi, type ChiState } from './state';
import { Select, TextInput, SharedImport, Reveal, f } from './ui';

export function ChiSquareTool() {
  const [s, set] = useToolState<ChiState>('chi-square'); const patch = (change: Partial<ChiState>) => set(old => ({ ...old, ...change }));
  const rawFit = s.parameterSource === 'sample' && s.fitMode === 'raw', supportsRawFit = ['binomial', 'poisson', 'normal'].includes(s.model);
  const gof = captured(() => s.mode === 'gof' ? goodnessOfFit(s) : undefined), g = gof.result;
  const contingency = captured(() => s.mode === 'independence' ? independence(s) : undefined), c = contingency.result;
  const r = g ?? c;
  const maxContribution = Math.max(...(g?.rows.map(row => row.contribution) ?? c?.contributions.flat() ?? []), .01);
  const xMax = r && r.df > 0 ? Math.max((r.critical ?? 1) * 1.6, Math.min(r.statistic * 1.2, 100), 8) : 10;
  const chiCurve = r && r.df > 0 ? Array.from({ length: 260 }, (_, i) => { const x = xMax * (i + 1) / 260, a = r.df / 2; return { x, y: Math.exp((a - 1) * Math.log(x) - x / 2 - a * Math.log(2) - logGamma(a)) }; }) : [];
  return <div className="inference-tool stats-stack"><div className="stats-grid"><Panel title="指定模型与数据来源"><div className="stats-stack"><Select label="χ² 检验类型" value={s.mode} onChange={mode => patch({ mode })} options={[["gof", "拟合优度"], ["independence", "列联表独立性"]]} />
  {s.mode === 'gof' ? <>{!rawFit && <TextInput label="各原类别观测频数 O" value={s.observed} onChange={observed => patch({ observed, groups: '' })} hint="每组一个非负整数。切点有 k 个时，必须提供 k+1 组，包括两端尾组。" />}<Select label="H₀ 概率模型" value={s.model} onChange={model => patch({ model, groups: '', fitMode: ['binomial', 'poisson', 'normal'].includes(model) ? s.fitMode ?? 'manual' : 'manual', estimatedCount: s.parameterSource === 'sample' ? rawFit ? model === 'normal' ? 2 : 1 : Math.min(s.estimatedCount, model === 'normal' ? 2 : model === 'given' ? 10 : 1) : 0 })} options={[["given", "给定类别概率"], ["binomial", "二项 B(n,p)"], ["poisson", "泊松 Po(λ)"], ["normal", "正态 N(μ,σ²)"], ["exponential", "连续指数模型"]]} />
  {s.model === 'given' ? <TextInput label="各类别模型概率（总和必须为 1）" value={s.probabilities} onChange={probabilities => patch({ probabilities, groups: '' })} /> : <><TextInput label="按升序填写分组切点" value={s.cutoffs} onChange={cutoffs => patch({ cutoffs, groups: '' })} rows={2} hint={s.model === 'binomial' || s.model === 'poisson' ? '整数切点 c 表示 P(X≤c)；最后一组是 X≥最后切点+1。' : '连续切点；首末组自动延伸至支持边界，包含全部概率。'} /><div className="stats-grid">
  {s.model === 'binomial' && <><NumberField label="每次试验的二项 n（固定）" value={s.trials} min={1} max={500} step={1} onChange={trials => patch({ trials })} />{!rawFit && <NumberField label="二项 p" value={s.probability} min={0} max={1} onChange={probability => patch({ probability })} />}</>}
  {s.model === 'poisson' && !rawFit && <NumberField label="泊松 λ" value={s.lambda} min={.01} max={200} onChange={lambda => patch({ lambda })} />}
  {s.model === 'normal' && !rawFit && <><NumberField label="正态 μ" value={s.mu} min={-1e9} max={1e9} onChange={mu => patch({ mu })} /><NumberField label="正态 σ" value={s.sigma} min={1e-8} max={1e8} onChange={sigma => patch({ sigma })} /></>}
  {s.model === 'exponential' && <NumberField label="指数发生率" value={s.rate} min={1e-8} max={1e8} onChange={rate => patch({ rate })} />}</div></>}
  <Select label="参数来源（影响自由度）" value={s.parameterSource} onChange={parameterSource => patch({ parameterSource, groups: '', estimatedCount: parameterSource === 'given' ? 0 : s.model === 'normal' ? 2 : 1 })} options={[["given", "题目给定／外部固定参数"], ["sample", "从本次观测样本估计"]]} />
  {s.parameterSource === 'sample' && <>{supportsRawFit && <Select label="同样本参数估计方式" value={s.fitMode ?? 'manual'} onChange={fitMode => patch({ fitMode, groups: '', estimatedCount: s.model === 'normal' ? 2 : 1 })} options={[["manual", "手工填写已有估计值"], ["raw", "原始同一批观测自动估参和分组"]]} />}{rawFit ? <><SharedImport onLoad={a => patch({ rawSample: a.join(', '), groups: '' })} /><TextInput label="用于估参及生成 O 的同一原始样本" value={s.rawSample ?? initialChi.rawSample!} onChange={rawSample => patch({ rawSample })} hint="2–200 个真实观测；共享导入采用样本 A。每个观测只进入一个分组，两端尾组自动包含。" /><Notice>O、模型参数和 E 都由这一批观测生成；手工 O 和参数栏不参与计算。不会用开放尾组的中点伪造原始数据或精确均值。参数个数 m 自动确定。</Notice></> : <><NumberField label="本样本估计的独立参数个数 m" value={s.estimatedCount} min={1} max={s.model === 'normal' ? 2 : s.model === 'given' ? 10 : 1} step={1} onChange={estimatedCount => patch({ estimatedCount })} /><Notice>请填入由本次样本估出的参数。本手工模式不从分组频数拟合，也不使用开放尾组中点推算精确均值。只扣除实际估计的参数；给定参数不扣除。正态均值与方差都估计时 m=2。</Notice></>}</>}
  <TextInput label="合并原类别（可用下方按钮）" value={s.groups} onChange={groups => patch({ groups: groups.trim() })} rows={2} hint="留空表示不合并。1,2|3|4 表示先合并第 1、2 类；必须按序完整覆盖原类别。" />
  </> : <><TextInput label="列联表观测频数（每行一行；逗号分列）" value={s.table} onChange={table => patch({ table, rowGroups: '', columnGroups: '' })} rows={5} /><Notice>H₀：两个分类变量独立。合并只能对整行或整列进行，不能任意合并单个单元格。结果不能解释成因果关系。</Notice><Formula value="E_{ij}=\frac{(\text{row total})_i(\text{column total})_j}{N}" /></>}
  <div className="stats-grid"><NumberField label="显著性 α" value={s.alpha} min={.0001} max={.3} onChange={alpha => patch({ alpha })} /><NumberField label="保持比例：所有 O 倍增" value={s.scale} min={1} max={100} step={1} onChange={scale => patch({ scale })} /></div><Notice>倍增后比例不变，但假想样本量与 χ² 都改变；表格显示乘倍后的频数。{rawFit ? '参数估计保持不变。这是课堂假想样本量实验，复制已有观测不能增加独立样本信息。' : '原始频数仍保存在输入框中。'}</Notice>
  </div></Panel><Panel title="先检查期望频数，再作结论"><div className="stats-stack">{(gof.error || contingency.error) && <Notice tone="warning">{gof.error || contingency.error}</Notice>}{r && <><div className="stats-results"><Result label="χ²=Σ(O−E)²/E" value={f(r.statistic)} /><Result label={g ? 'df=k−1−m' : 'df=(r−1)(c−1)'} value={r.df} /><Result label="N" value={r.total} /><Result label="右尾 p 值" value={f(r.pValue)} note={r.valid ? undefined : '仅显示参考数值，近似检验条件未通过'} /><Result label="右尾临界值" value={f(r.critical)} /><Result label="判决" value={r.reject === undefined ? '不给有效检验结论' : r.reject ? '拒绝 H₀' : '不拒绝 H₀'} /></div>
  {r.reasons.map(reason => <Notice tone="warning" key={reason}>{reason}</Notice>)}
  {g?.fit && <><div className="stats-results">{g.fit.parameters.map(parameter => <Result key={parameter.name} label={parameter.name} value={f(parameter.value)} />)}<Result label="自动扣除的参数个数 m" value={g.fit.estimated} /><Result label="原始观测数（倍增前）" value={g.fit.values.length} /></div><Notice>{g.fit.convention}</Notice></>}
  <Reveal>{r.df > 0 && <Plot series={[{ kind: 'line', name: `χ²(${r.df})`, data: chiCurve }, { kind: 'line', name: '右尾拒绝域', color: 'var(--danger)', data: chiCurve.filter(p => p.x >= (r.critical ?? Infinity)) }]} xDomain={[0, xMax]} xLabel="χ² 统计量" yLabel="密度" markers={[{ x: r.statistic, label: r.statistic > xMax ? undefined : '观测 χ²', color: 'var(--stats-blue)' }, { x: r.critical ?? Infinity, label: '右尾临界界', color: 'var(--danger)' }]} />}{r.statistic > xMax && <Notice>观测 χ²={f(r.statistic)} 超出此密度图横轴范围。</Notice>}{r.reject !== undefined && <Notice>{conclusion(r.reject)} {g ? '目标是检验所指定的整套类别概率模型。' : '仅反映关联证据，不证明因果。'}</Notice>}</Reveal><Notice>课程模式要求每个最终 E≥5。不提供 Yates 连续性修正作为默认或必选方法。</Notice></>}
  </div></Panel></div>
  {g && <Panel title="原频数 → 合并 O、E → 重算贡献"><div className="stats-stack"><div className="stats-toolbar">{g.groups.slice(0, -1).map((_, i) => <button type="button" className="stats-button" key={i} onClick={() => patch({ groups: serializeGroups(mergeAdjacent(g.groups, i)) })}>合并现组 {i + 1} 与 {i + 2}</button>)}<button className="stats-button" type="button" onClick={() => patch({ groups: '' })}>恢复全部原组</button></div><Reveal><div className="inference-table-wrap"><table className="stats-table"><thead><tr><th>最终类别</th><th>O</th><th>模型概率</th><th>E</th><th>(O−E)²/E</th></tr></thead><tbody>{g.rows.map((row, i) => <tr key={i}><td>{row.label}</td><td>{row.observed}</td><td>{f(row.probability)}</td><td style={{ color: row.expected < 5 ? 'var(--danger)' : undefined }}>{f(row.expected)}{row.expected < 5 ? ' ⚠' : ''}</td><td style={{ background: `rgba(196,83,108,${.08 + .35 * row.contribution / maxContribution})` }}>{f(row.contribution)}</td></tr>)}</tbody></table></div><Plot series={[{ kind: 'bar', barWidth: .38, name: '观测 O', data: g.rows.map((row, i) => ({ x: i + 1 - .2, y: row.observed })) }, { kind: 'bar', barWidth: .38, name: '期望 E', color: 'var(--stats-gold)', data: g.rows.map((row, i) => ({ x: i + 1 + .2, y: row.expected })) }]} xLabel="最终类别编号" yLabel="频数" /></Reveal><Notice>合并时重新计算 (ΣO−ΣE)²/ΣE，不能把旧贡献相加。当前最终组数 {g.rows.length}，参数来源：{s.parameterSource === 'given' ? '题目／外部给定' : `本样本估计 ${g.estimated} 个参数`}。</Notice></div></Panel>}
  {c && <Panel title="O / E 与贡献热图：颜色越深，贡献越大"><div className="stats-stack"><div className="stats-toolbar">{c.rowGroups.slice(0, -1).map((_, i) => <button type="button" className="stats-button" key={`r${i}`} onClick={() => patch({ rowGroups: serializeGroups(mergeAdjacent(c.rowGroups, i)) })}>合并现行 {i + 1} 与 {i + 2}</button>)}{c.columnGroups.slice(0, -1).map((_, i) => <button type="button" className="stats-button" key={`c${i}`} onClick={() => patch({ columnGroups: serializeGroups(mergeAdjacent(c.columnGroups, i)) })}>合并现列 {i + 1} 与 {i + 2}</button>)}<button type="button" className="stats-button" onClick={() => patch({ rowGroups: '', columnGroups: '' })}>恢复原表</button></div><Reveal><div className="inference-table-wrap"><table className="stats-table"><thead><tr><th>行 / 列</th>{c.columnGroups.map((group, j) => <th key={j}>原列 {group.map(i => i + 1).join('+')}</th>)}<th>行和</th></tr></thead><tbody>{c.observed.map((row, i) => <tr key={i}><th>原行 {c.rowGroups[i].map(k => k + 1).join('+')}</th>{row.map((o, j) => <td className="inference-heat-cell" key={j} style={{ background: `rgba(196,83,108,${.07 + .42 * c.contributions[i][j] / maxContribution})` }}><strong>O {o} / E {f(c.expected[i][j])}</strong><small>贡献 {f(c.contributions[i][j])}{c.expected[i][j] < 5 ? '；E<5 ⚠' : ''}</small></td>)}<th>{c.rowTotals[i]}</th></tr>)}<tr><th>列和</th>{c.columnTotals.map((total, j) => <th key={j}>{total}</th>)}<th>{c.total}</th></tr></tbody></table></div></Reveal><Notice>每次合并整行或整列后重新计算边际、E、贡献与 df；只有剩余至少两行两列且 E 条件通过时才能给结论。</Notice></div></Panel>}
  </div>;
}
