import { Panel, NumberField, Result, Notice, Plot, Formula } from '../shared';
import { useStatisticsWorkspace, useToolState } from '../workspace';
import { captured, conclusion } from './common';
import { meanInference, standardDensity } from './means';
import type { MeanState } from './state';
import { Check, Select, TextInput, TailSelect, SharedImport, Reveal, relation, f } from './ui';

export function MeansTool() {
  const [s, set] = useToolState<MeanState>('means'); const { share, navigate } = useStatisticsWorkspace();
  const patch = (change: Partial<MeanState>) => set(old => ({ ...old, ...change }));
  const calculated = captured(() => meanInference(s)), r = calculated.result;
  const target = s.design === 'single' ? 'μ' : s.design === 'paired' ? 'μ_d（d=A−B）' : 'μ_A−μ_B';
  const density = (df?: number) => Array.from({ length: 241 }, (_, i) => { const x = -6 + i / 20; return { x, y: standardDensity(x, df) }; });
  return <div className="inference-tool stats-stack"><div className="stats-grid"><Panel title="先选择设计，再核实条件"><div className="stats-stack"><Select label="样本设计" value={s.design} onChange={design => patch({ design })} options={[["single", "单样本"], ["paired", "配对样本（A−B）"], ["independent", "独立两样本（A−B）"]]} /><SharedImport paired={s.design === 'paired'} onLoad={(a, b) => patch({ sample: a.join(', '), ...(b ? { sample2: b.join(', ') } : {}) })} /><TextInput label="样本 A" value={s.sample} onChange={sample => patch({ sample })} hint="原始数据；2–200 个观测。所有 s² 使用 n−1 分母。" />{s.design !== 'single' && <TextInput label="样本 B" value={s.sample2} onChange={sample2 => patch({ sample2 })} hint={s.design === 'paired' ? '保持每一对的行次序；不是自动排序配对。' : '另一组独立随机样本。'} />}
  <Check label={s.design === 'paired' ? '确认：差值总体正态' : s.design === 'single' ? '确认：总体正态' : '确认：两个总体均正态'} checked={s.normal} onChange={normal => patch({ normal })} />
  {s.design !== 'paired' && <><Check label="总体方差已知" checked={s.known} onChange={known => patch({ known })} /><Check label="具有大样本 CLT 的条件" checked={s.large} onChange={large => patch({ large })} />{s.design === 'independent' && !s.known && <Check label="有共同未知方差的条件（pooled t）" checked={s.equalVariance} onChange={equalVariance => patch({ equalVariance })} />}{s.known && <div className="stats-grid"><NumberField label="已知 σ_A" value={s.sigma} min={1e-8} max={1e8} onChange={sigma => patch({ sigma })} />{s.design === 'independent' && <NumberField label="已知 σ_B" value={s.sigma2} min={1e-8} max={1e8} onChange={sigma2 => patch({ sigma2 })} />}</div>}</>}
  <Notice>随机抽样、样本内部独立需要来自研究设计，勾选条件不是数据自动证明条件。切换配对与独立会改变研究设计，n 相等不足以支持配对。</Notice>
  <div className="stats-grid"><NumberField label={`H₀：${target} 等于`} value={s.nullValue} min={-1e9} max={1e9} onChange={nullValue => patch({ nullValue })} /><NumberField label="显著性 α" value={s.alpha} min={.0001} max={.3} onChange={alpha => patch({ alpha })} /></div><TailSelect value={s.tail} onChange={tail => patch({ tail })} />
  </div></Panel><Panel title="方法选择与推断"><div className="stats-stack">{calculated.error && <Notice tone="warning">{calculated.error}</Notice>}{r && <><Notice>所选条件对应 {r.method}。{r.reason}</Notice><Formula value="T=\frac{\widehat\theta-\theta_0}{\operatorname{SE}(\widehat\theta)}" /><div className="stats-results"><Result label="目标估计值" value={f(r.estimate)} /><Result label="标准误 SE" value={f(r.se)} /><Result label="统计量 / 自由度" value={`${f(r.statistic)} / ${r.df ?? '正态，无 t 自由度'}`} /><Result label="p 值" value={f(r.pValue)} />{r.pooledVariance !== undefined && <Result label="合并方差 sₚ²" value={f(r.pooledVariance)} />}<Result label={`${f(100 * (1 - s.alpha))}% 双侧置信区间`} value={`[${f(r.low)}, ${f(r.high)}]`} /></div>
  <Reveal><Plot series={[{ kind: 'line', data: density(r.df), name: r.df === undefined ? '标准正态' : `t(${r.df})` }, { kind: 'line', data: density(r.df).filter(p => s.tail !== 'upper' && p.x <= -r.critical), color: 'var(--danger)', name: '拒绝域尾部' }, { kind: 'line', data: density(r.df).filter(p => s.tail !== 'lower' && p.x >= r.critical), color: 'var(--danger)' }]} xLabel="H₀ 下的标准化统计量" markers={[{ x: r.statistic, label: '观测', color: 'var(--stats-blue)' }, ...(s.tail !== 'upper' ? [{ x: -r.critical, label: '临界值', color: 'var(--danger)' }] : []), ...(s.tail !== 'lower' ? [{ x: r.critical, label: '临界值', color: 'var(--danger)' }] : [])]} /><Notice>H₁：{target} {relation(s.tail)} {f(s.nullValue)}。{conclusion(r.reject)}</Notice>{r.duality ? <Notice>方法、标准误、假设条件与 α 完全匹配：H₀ 值位于 {(1 - s.alpha) * 100}% 双侧区间内部 ⇔ 双侧检验不拒绝 H₀。当前{r.nullInside ? '位于内部' : '不在内部'}。数值恰在端点时，本工具按 p≤α 的边界约定拒绝。</Notice> : <Notice>当前是单尾检验，因此不把此双側区间解释为它的对偶；所示区间仅用于估计。</Notice>}</Reveal>
  <button type="button" className="stats-button" onClick={() => { share({ sample: s.design === 'paired' ? r.differences : r.a, ...(s.design === 'independent' ? { secondSample: r.b, design: 'independent' as const } : { design: 'single' as const }), label: s.design === 'paired' ? 'A−B 配对差' : '均值推断样本' }); navigate('intervals'); }}>将{s.design === 'paired' ? '配对差' : '样本'}送到区间工具</button></>}
  </div></Panel></div>
  {r && s.design !== 'single' && <Panel title={s.design === 'paired' ? '配对关系：每条线连接同一对' : '独立样本：两组点云，没有人为配对连线'}><Reveal><div className="stats-grid"><Plot height={330} series={s.design === 'paired' ? r.a.map((value, i) => ({ kind: 'line' as const, color: 'color-mix(in srgb, var(--success) 56%, transparent)', data: [{ x: 0, y: value }, { x: 1, y: r.b[i] }] })).concat([{ kind: 'line' as const, color: 'transparent', data: [] }]) : [{ kind: 'points', name: '样本 A', data: r.a.map((y, i) => ({ x: -.08 + .16 * ((i * 17 % 29) / 29), y })) }, { kind: 'points', name: '样本 B', color: 'var(--stats-gold)', data: r.b.map((y, i) => ({ x: .92 + .16 * ((i * 17 % 29) / 29), y })) }]} xDomain={[-.2, 1.2]} xLabel="0=样本 A；1=样本 B" yLabel="观测值" /><div className="inference-pair-list"><table className="stats-table"><thead><tr><th>序号</th><th>A</th><th>B</th>{s.design === 'paired' && <th>d=A−B</th>}</tr></thead><tbody>{Array.from({ length: Math.max(r.a.length, r.b.length) }, (_, i) => <tr key={i}><td>{i + 1}</td><td>{f(r.a[i])}</td><td>{f(r.b[i])}</td>{s.design === 'paired' && <td>{f(r.differences[i])}</td>}</tr>)}</tbody></table></div></div></Reveal></Panel>}
  <Panel title="自由度探究：t 的尾部如何接近正态"><div className="stats-grid"><div className="stats-stack"><NumberField label="用于比较的 t 自由度" value={s.viewDf} min={1} max={200} step={1} onChange={viewDf => patch({ viewDf })} /><input aria-label="调节 t 自由度" type="range" min={1} max={100} step={1} value={Math.min(100, s.viewDf)} onChange={e => patch({ viewDf: Number(e.target.value) })} /><Notice>这幅比较图的自由度只控制教学曲线，不修改当前检验的自由度。自由度小的 t 有更厚的尾部，因此相同置信度通常需要更大的临界值。</Notice><Notice>Welch t 不作为现行 FS 核心方法；没有共同方差且样本较小时，这里保留数据并提示条件不足。</Notice></div><Reveal><Plot series={[{ kind: 'line', data: density(), name: 'N(0,1)' }, { kind: 'line', data: density(s.viewDf), name: `t(${s.viewDf})`, color: 'var(--stats-gold)' }]} xLabel="标准化值" yLabel="密度" /></Reveal></div></Panel>
  </div>;
}
