import { Panel, NumberField, Result, Notice, Plot, Formula } from '../shared';
import { useToolState } from '../workspace';
import { captured, conclusion } from './common';
import { rankInference } from './ranks';
import { standardDensity } from './means';
import type { RankState } from './state';
import { Select, TextInput, TailSelect, SharedImport, Reveal, relation, f } from './ui';

export function RanksTool() {
  const [s, set] = useToolState<RankState>('ranks'); const patch = (change: Partial<RankState>) => set(old => ({ ...old, ...change }));
  const calculated = captured(() => rankInference(s)), r = calculated.result;
  const label = s.method === 'sign' ? '正号数 S' : s.method === 'signedrank' ? '正秩和 W⁺' : 'A 组秩和 R_A';
  const target = s.design === 'single' ? '总体中位数' : s.design === 'paired' ? '配对差 A−B 的中位数' : '位置差（A−B）';
  const density = r ? Array.from({ length: 241 }, (_, i) => { const x = r.expected + (i / 30 - 4) * r.sd; return { x, y: standardDensity((x - r.expected) / r.sd) / r.sd }; }) : [];
  return <div className="inference-tool stats-stack"><div className="stats-grid"><Panel title="设计、中位数目标与方法"><div className="stats-stack"><Select label="样本设计" value={s.design} onChange={design => patch({ design, method: design === 'independent' ? 'ranksum' : s.method === 'ranksum' ? 'signedrank' : s.method })} options={[["single", "单样本中位数"], ["paired", "配对差中位数"], ["independent", "独立两样本位置比较"]]} /><Select label="检验方法" value={s.method} onChange={method => patch({ method })} options={s.design === 'independent' ? [["ranksum", "Wilcoxon 秩和"]] : [["sign", "符号检验"], ["signedrank", "Wilcoxon 符号秩"]]} />
  <SharedImport paired={s.design === 'paired'} onLoad={(a, b) => patch({ sample: a.join(', '), ...(b ? { sample2: b.join(', ') } : {}) })} /><TextInput label="样本 A（保留原顺序）" value={s.sample} onChange={sample => patch({ sample })} />{s.design !== 'single' && <TextInput label="样本 B" value={s.sample2} onChange={sample2 => patch({ sample2 })} />}
  <div className="stats-grid"><NumberField label={`H₀：${target} 等于`} value={s.median} min={-1e9} max={1e9} onChange={median => patch({ median })} /><NumberField label="显著性 α" value={s.alpha} min={.0001} max={.3} onChange={alpha => patch({ alpha })} /></div><TailSelect value={s.tail} onChange={tail => patch({ tail })} /><Select label="分布计算" value={s.approximation} onChange={approximation => patch({ approximation })} options={[["auto", "小样本精确；超出上限后正态近似"], ["normal", "无 ties 正态近似（连续性修正）"]]} />
  <Notice>{s.method === 'sign' ? '符号检验只使用差值正负，不要求总体对称；H₀ 下正号数服从 B(n,0.5)。' : s.method === 'signedrank' ? 'FS 口径：总体（配对时为差值总体）连续且对称；按绝对差排序，再恢复符号。' : 'FS 口径：两独立连续、对称总体；作为中位数／位置比较时还需共同形状与尺度，仅有中位数相同不足以保证可交换。非零假设位置差先从 A 组减去。'}</Notice>
  {s.design === 'paired' && <Notice>差值中位数一般不等于两个边际中位数之差。每一对的顺序由设计确定，不能排序后人为配对。</Notice>}
  <Notice>课程模式阻止零差、等于假设中位数以及秩检验中的并列秩，不静默删值或补平均秩。符号检验可接受非零重复值，因为它不使用秩。</Notice>
  </div></Panel><Panel title="精确分布／近似分布与检验"><div className="stats-stack">{calculated.error && <Notice tone="warning">{calculated.error}</Notice>}{r && <><Notice>{r.exact ? '当前使用可枚举分布的精确概率。' : '当前使用无 ties 方差的正态近似。'} 精确上限：符号 n≤100；符号秩 n≤25；秩和两组合计≤40。双尾固定采用各 α/2 等尾规则。</Notice><div className="stats-results"><Result label={label} value={r.statistic} /><Result label="H₀ 期望 / 方差" value={`${f(r.expected)} / ${f(r.variance)}`} /><Result label="p 值" value={f(r.pValue)} /><Result label="实际 α（仅精确分布）" value={f(r.actualAlpha)} /><Result label="判决" value={r.reject ? '拒绝 H₀' : '不拒绝 H₀'} />{r.negativeSum !== undefined && <Result label="W⁻ / W⁺+W⁻" value={`${r.negativeSum} / ${r.totalRanks}`} />}{r.reverseSum !== undefined && <><Result label="A 组反向秩和" value={r.reverseSum} note="m(m+n+1)−R_A" /><Result label="B 组实际秩和" value={r.otherGroupSum} note="全部秩和−R_A；通常不同于 A 的反向秩和" /></>}</div>
  <Reveal><Plot series={r.masses ? [{ kind: 'bar', barWidth: 1, name: '精确零假设分布', data: r.masses.map((y, x) => ({ x, y })) }, { kind: 'bar', barWidth: 1, name: '拒绝域 R', color: 'var(--danger)', data: r.masses.map((p, x) => ({ x, y: x <= r.lower || x >= r.upper ? p : 0 })) }] : [{ kind: 'line', name: '正态近似密度', data: density }, { kind: 'line', name: '下尾拒绝区域', color: 'var(--danger)', data: density.filter(p => p.x <= r.lower + .5) }, { kind: 'line', name: '上尾拒绝区域', color: 'var(--danger)', data: density.filter(p => p.x >= r.upper - .5) }]} xLabel={label} yLabel={r.exact ? '概率' : '近似密度'} markers={[{ x: r.statistic, label: '观测统计量', color: 'var(--stats-blue)' }, { x: r.lower, label: '下尾整数界', color: 'var(--danger)' }, { x: r.upper, label: '上尾整数界', color: 'var(--danger)' }]} /><Notice>H₁：{target} {relation(s.tail)} {f(s.median)}。{conclusion(r.reject)}</Notice>{!r.exact && <Notice>连续性修正对应包含观测的离散事件：P(T≤{r.statistic})≈Φ(({r.statistic}+0.5−{f(r.expected)})/{f(r.sd)})；P(T≥{r.statistic})≈1−Φ(({r.statistic}−0.5−{f(r.expected)})/{f(r.sd)})。双尾取 2×较小尾概率，上限为 1。</Notice>}</Reveal>{r.warnings.map(warning => <Notice key={warning} tone="warning">{warning}</Notice>)}</>}
  </div></Panel></div>
  {r && <Panel title={s.method === 'ranksum' ? '合并排名，保留组别与原行号' : '原值 → 差值 → 绝对差 → 秩 → 符号'}><Reveal><div className="stats-grid"><div className="inference-table-wrap inference-pair-list"><table className="stats-table"><thead><tr><th>组／原序号</th><th>原值</th>{s.design === 'paired' && <th>配对 B</th>}<th>{s.method === 'ranksum' ? '平移后值' : '差值'}</th><th>|差值|</th><th>秩／符号</th></tr></thead><tbody>{r.rows.map(row => <tr key={`${row.group}${row.index}`}><td>{row.group}{row.index + 1}</td><td>{f(row.value)}</td>{s.design === 'paired' && <td>{f(row.other)}</td>}<td>{f(row.difference)}</td><td>{f(row.absolute)}</td><td style={{ color: s.method === 'ranksum' ? row.group === 'A' ? 'var(--success)' : 'var(--stats-gold)' : row.positive ? 'var(--success)' : 'var(--danger)' }}>{s.method === 'sign' ? row.positive ? '+' : '−' : s.method === 'ranksum' ? row.rank : `${row.positive ? '+' : '−'}${row.rank}`}</td></tr>)}</tbody></table></div>{s.method === 'ranksum' ? <Plot series={[{ kind: 'points', name: 'A 组', data: r.rows.filter(row => row.group === 'A').map(row => ({ x: row.rank!, y: row.difference })) }, { kind: 'points', name: 'B 组', color: 'var(--stats-gold)', data: r.rows.filter(row => row.group === 'B').map(row => ({ x: row.rank!, y: row.difference })) }]} xLabel="合并后秩" yLabel="用于排名的值" /> : <Plot series={[{ kind: 'bar', barWidth: 1, name: s.method === 'sign' ? '正号 +1' : '正秩', data: r.rows.map(row => ({ x: row.index + 1, y: row.positive ? s.method === 'sign' ? 1 : row.rank! : 0 })) }, { kind: 'bar', barWidth: 1, name: s.method === 'sign' ? '负号 −1' : '负秩', color: 'var(--danger)', data: r.rows.map(row => ({ x: row.index + 1, y: !row.positive ? s.method === 'sign' ? -1 : -row.rank! : 0 })) }]} xLabel="原始行号（不因排序而改变）" yLabel={s.method === 'sign' ? '符号' : '带符号的秩'} />}</div></Reveal>{s.method === 'signedrank' && <Formula value="W^++W^-=\frac{n(n+1)}2" />}{s.method === 'ranksum' && <Formula value="R_{A,\mathrm{reverse}}=m(m+n+1)-R_A\ne R_B\text{ in general}" />}<Notice>左表始终保留原始行对应，秩来自排序后的参考顺序；更换尾部只更换拒绝方向，不重新排名。</Notice></Panel>}
  </div>;
}
