import { Panel, NumberField, Result, Notice, Plot } from '../shared';
import { useToolState } from '../workspace';
import { captured, conclusion } from './common';
import { compatiblePRange, discreteTest, invertDiscreteBoundary, zTest } from './hypothesis';
import { standardDensity } from './means';
import type { TestState } from './state';
import { Select, TailSelect, Reveal, relation, f } from './ui';

export function TestsTool() {
  const [s, set] = useToolState<TestState>('tests'); const patch = (change: Partial<TestState>) => set(old => ({ ...old, ...change }));
  const discrete = captured(() => s.model === 'z' ? undefined : discreteTest(s)), d = discrete.result;
  const continuous = captured(() => s.model === 'z' ? zTest(s) : undefined), z = continuous.result;
  const r = d ?? z, theta0 = s.model === 'binomial' ? s.p0 : s.model === 'poisson' ? s.lambda0 : s.mean0, theta1 = s.model === 'binomial' ? s.p1 : s.model === 'poisson' ? s.lambda1 : s.mean1;
  const properAlternative = s.tail === 'upper' ? theta1 > theta0 : s.tail === 'lower' ? theta1 < theta0 : theta1 !== theta0;
  const inverseSides = s.tail === 'two' ? ['lower', 'upper'] as const : [s.tail] as ('lower' | 'upper')[];
  const inverses = s.model === 'z' ? [] : inverseSides.map(side => ({ side, ...captured(() => invertDiscreteBoundary(s.model as 'binomial' | 'poisson', s.n, s.observed, s.tail === 'two' ? s.alpha / 2 : s.alpha, side)) }));
  const max = d ? Math.max(s.observed + 1, ...d.masses.map((p, k) => p > 1e-7 ? k : 0), ...d.alternative.map((p, k) => p > 1e-7 ? k : 0)) : 1;
  const plotShift = Math.max(-12, Math.min(12, z?.shift ?? 0));
  const curve = (shift: number) => Array.from({ length: 281 }, (_, i) => { const x = Math.min(-4.5, plotShift - 4.5) + i / 280 * (Math.max(4.5, plotShift + 4.5) - Math.min(-4.5, plotShift - 4.5)); return { x, y: standardDensity(x - shift) }; });
  const regionLabel = r ? [(d ? d.lower >= 0 : Number.isFinite(r.lower)) ? `T ≤ ${f(r.lower)}` : '', Number.isFinite(r.upper) ? `T ≥ ${f(r.upper)}` : ''].filter(Boolean).join(' 或 ') || '空集' : '';
  const band = compatiblePRange(.05, .01);
  return <div className="inference-tool stats-stack"><div className="stats-grid"><Panel title="先定义假设和拒绝规则"><div className="stats-stack"><Select label="检验模型" value={s.model} onChange={model => patch({ model, observed: model === 'z' ? s.mean0 + 2 * s.se : model === 'binomial' ? Math.min(s.n, 15) : 9 })} options={[["binomial", "二项比例检验"], ["poisson", "泊松率检验"], ["z", "均值 z 检验"]]} />
  {s.model === 'binomial' ? <div className="stats-grid"><NumberField label="试验次数 n" value={s.n} min={1} max={500} step={1} onChange={n => patch({ n, observed: Math.min(n, s.observed) })} /><NumberField label="H₀ 比例 p₀" value={s.p0} min={.0001} max={.9999} onChange={p0 => patch({ p0 })} /><NumberField label="具体备择 p₁" value={s.p1} min={0} max={1} onChange={p1 => patch({ p1 })} /></div> : s.model === 'poisson' ? <div className="stats-grid"><NumberField label="H₀ 每观察区间均数 λ₀" value={s.lambda0} min={.01} max={200} onChange={lambda0 => patch({ lambda0 })} /><NumberField label="具体备择 λ₁（同区间）" value={s.lambda1} min={.01} max={200} onChange={lambda1 => patch({ lambda1 })} /></div> : <div className="stats-grid"><NumberField label="H₀ 总体均值 μ₀" value={s.mean0} min={-1e9} max={1e9} onChange={mean0 => patch({ mean0 })} /><NumberField label="具体备择总体均值 μ₁" value={s.mean1} min={-1e9} max={1e9} onChange={mean1 => patch({ mean1 })} /><NumberField label="已知或大样本近似标准误 SE" value={s.se} min={1e-8} max={1e8} onChange={se => patch({ se })} /></div>}
  <TailSelect value={s.tail} onChange={tail => patch({ tail })} /><div className="stats-grid"><NumberField label="标称显著性 α" value={s.alpha} min={.0001} max={.3} onChange={alpha => patch({ alpha })} /><NumberField label={s.model === 'z' ? '观测样本均值' : '观测计数 k'} value={s.observed} min={s.model === 'z' ? -1e9 : 0} max={s.model === 'binomial' ? s.n : s.model === 'z' ? 1e9 : 1000} step={s.model === 'z' ? 'any' : 1} onChange={observed => patch({ observed })} /></div>
  {s.model !== 'z' && <input aria-label="移动观测计数" type="range" min={0} max={s.model === 'binomial' ? s.n : Math.min(1000, Math.ceil(s.lambda0 + 5 * Math.sqrt(s.lambda0) + 5))} step={1} value={s.observed} onChange={e => patch({ observed: Number(e.target.value) })} />}
  <Notice>H₀：{s.model === 'binomial' ? 'p' : s.model === 'poisson' ? 'λ' : 'μ'}={f(theta0)}；H₁：{s.model === 'binomial' ? 'p' : s.model === 'poisson' ? 'λ' : 'μ'} {relation(s.tail)} {f(theta0)}。{s.model === 'binomial' ? '固定 n，独立同概率 Bernoulli 试验。' : s.model === 'poisson' ? '恒定发生率、不相交区间独立；λ 是同一个观察区间内的均数。' : '独立样本且总体正态、σ 已知，或大样本 CLT 近似；SE=σ/√n 或近似 s/√n。'}</Notice>
  {s.tail === 'two' && <Notice>双尾规则明确固定：每尾分配 α/2。显示的 p 值为在此等尾规则族下 2×较小包含观测的尾概率（上限 1），不使用概率排序双尾规则。</Notice>}
  </div></Panel><Panel title="固定拒绝域 R，比较两个分布"><div className="stats-stack">{(discrete.error || continuous.error) && <Notice tone="warning">{discrete.error || continuous.error}</Notice>}
  {r && <><Reveal>{d ? <Plot series={[{ kind: 'bar', barWidth: 1, name: 'H₀ 的计数概率', data: d.masses.map((y, x) => ({ x, y })) }, { kind: 'bar', barWidth: 1, color: 'var(--danger)', name: 'H₀ 下落在 R（第一类错误）', data: d.masses.map((p, x) => ({ x, y: d.rejects(x) ? p : 0 })) }, { kind: 'line', color: 'var(--stats-gold)', name: '具体参数 θ₁ 下的分布', data: d.alternative.map((y, x) => ({ x, y })) }]} xDomain={[-.6, max + .6]} xLabel="观测计数" yLabel="概率" markers={[{ x: s.observed, label: '观测', color: 'var(--stats-blue)' }, ...(d.lower >= 0 ? [{ x: d.lower + .5, label: '下尾边界', color: 'var(--danger)' }] : []), ...(Number.isFinite(d.upper) ? [{ x: d.upper - .5, label: '上尾边界', color: 'var(--danger)' }] : [])]} /> : z && <Plot series={[{ kind: 'line', name: 'H₀: N(0,1)', data: curve(0) }, { kind: 'line', name: 'θ₁ 下标准化统计量', data: curve(z.shift), color: 'var(--stats-gold)' }, { kind: 'line', name: 'H₀ 下拒绝域', data: curve(0).filter(p => p.x <= z.lower), color: 'var(--danger)' }, { kind: 'line', data: curve(0).filter(p => p.x >= z.upper), color: 'var(--danger)' }]} xLabel="z=(x̄−μ₀)/SE" markers={[{ x: z.statistic, label: '观测 z', color: 'var(--stats-blue)' }, { x: z.lower, label: '下界', color: 'var(--danger)' }, { x: z.upper, label: '上界', color: 'var(--danger)' }]} />}</Reveal>
  <div className="stats-results"><Result label="拒绝域 R" value={regionLabel} /><Result label="实际第一类错误 P₀(R)" value={f(r.actualAlpha)} note={`标称 α=${s.alpha}`} /><Result label="所选规则下 p 值" value={f(r.pValue)} /><Result label={properAlternative ? '功效 Pθ₁(R)' : '所选参数下拒绝概率'} value={f(r.power)} /><Result label={properAlternative ? 'β=Pθ₁(R 外)' : '所选参数下不拒绝概率'} value={f(r.beta)} /><Result label="判决" value={r.reject ? '拒绝 H₀' : '不拒绝 H₀'} /></div><Reveal><Notice>{conclusion(r.reject)}</Notice>{z && Math.abs(z.shift) > 12 && <Notice>备择分布中心超出当前绘图范围；功效仍按完整分布计算。</Notice>}</Reveal>
  {!properAlternative && <Notice tone="warning">θ₁ 不在当前 H₁ 的参数范围内。图中仍计算该参数下的拒绝概率，但不能称为当前 H₁ 下的功效。</Notice>}
  <Notice>改变 θ₁ 时，R 始终按 H₀ 与 α 保持不变。第一类错误发生于 H₀ 为真；第二类错误必须相对于一个具体的 H₁ 参数。教材中的“accept H₀”在这里表述为“不拒绝 H₀”。</Notice>
  {d && <Reveal><div className="inference-critical">{s.tail !== 'upper' && <p>下尾再纳入一个整数：P₀(T≤{d.lower + 1})={f(d.lowerNext)}，超过尾部预算 {f(d.budget)}。</p>}{s.tail !== 'lower' && d.upperPrevious !== undefined && <p>上尾再纳入一个整数：P₀(T≥{d.upper - 1})={f(d.upperPrevious)}，超过尾部预算 {f(d.budget)}。</p>}<p>整数概率柱不能切成半根，因此实际 α 往往小于标称值。泊松图仅截断绘图与求和的极小尾部（本参数范围小于 10⁻¹²）。</p></div></Reveal>}</>}
  </div></Panel></div><Panel title="从结论和临界界反求"><div className="stats-grid"><div><Result label="若在 5% 拒绝、1% 不拒绝" value={`${band.lowerExclusive} < p ≤ ${band.upperInclusive}`} note="两次必须使用同一检验与同一尾部规则，拒绝约定为 p≤α。" /><Notice>固定观测边界 k，反求 H₀ 参数使包含 k 的尾概率恰为所分配的 α。边界等式不代表任意备择分布下都有相同拒绝概率。</Notice></div><div className="stats-stack">{inverses.map(v => <div key={v.side}>{v.result ? <Result label={`${v.side === 'lower' ? '下尾' : '上尾'}边界参数 ${s.model === 'binomial' ? 'p₀' : 'λ₀'}`} value={f(v.result.parameter)} note={`代回尾概率 ${f(v.result.tailProbability)}`} /> : <Notice>{v.error}</Notice>}</div>)}{z && inverseSides.map(side => <Result key={side} label={`${side === 'upper' ? '上尾' : '下尾'}边界对应 μ₀`} value={f(s.observed + (side === 'upper' ? -1 : 1) * z.critical * s.se)} />)}</div></div></Panel></div>;
}
