import { chromium } from 'file:///C:/Users/17157/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:'C:/Users/17157/AppData/Local/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-win64/chrome-headless-shell.exe'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173/pure.html');await page.waitForTimeout(700);
async function setFormula(i,value){ await page.locator('math-field').nth(i).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},value);await page.waitForTimeout(200); }
await setFormula(0,'x^2');await setFormula(1,'1');
await page.getByRole('switch',{name:'启用图像分析'}).check();
await page.getByRole('button',{name:'取区域',exact:true}).click();
const canvas=page.locator('canvas').first();const box=await canvas.boundingBox();
await page.mouse.click(box.x+box.width/2,box.y+box.height/2-26);
await page.waitForTimeout(300);
assert.match(await page.locator('.cut-analysis').innerText(),/1.333333/);
await page.screenshot({path:'research/cut-analysis-qa/region-desktop.png'});
await page.getByRole('button',{name:'取曲线段',exact:true}).click();
await page.mouse.click(box.x+box.width/2+26,box.y+box.height/2-13);
await page.getByRole('textbox',{name:'曲线积分密度'}).fill('x^2+y^2');
await page.waitForTimeout(200);
assert.match(await page.locator('.cut-analysis').innerText(),/2.957886/);
await page.screenshot({path:'research/cut-analysis-qa/segment-desktop.png'});
await page.mouse.move(box.x+box.width/2,box.y+box.height/2+150);await page.mouse.down();await page.mouse.move(box.x+box.width/2+80,box.y+box.height/2+150,{steps:8});await page.mouse.up();
assert.match(await page.locator('.cut-analysis').innerText(),/2.957886/);
await setFormula(0,'x^2+0.2');
assert.equal(await page.getByRole('textbox',{name:'曲线积分密度'}).count(),0);
await page.getByRole('button',{name:'取区域',exact:true}).click();
await page.getByRole('button',{name:'取区域 1',exact:true}).click();
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);
await page.getByRole('button',{name:'图像分析',exact:true}).click();
await page.waitForTimeout(200);
assert.ok(await page.getByRole('button',{name:'取区域 1',exact:true}).isVisible());
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth > window.innerWidth),false);
await page.screenshot({path:'research/cut-analysis-qa/region-mobile.png'});
await page.getByRole('button',{name:'取曲线段',exact:true}).click();
await page.getByRole('button',{name:'曲线 1 曲线段',exact:true}).click();
await page.getByRole('textbox',{name:'曲线积分密度'}).fill('1');
await page.screenshot({path:'research/cut-analysis-qa/segment-mobile.png'});
console.log('PASS: canvas region/segment clicks, numerical values, pan retention, formula invalidation, mobile controls and overflow');
console.log('ERRORS',errors);assert.equal(errors.length,0);
await page.screenshot({path:'research/cut-analysis-qa/mobile-initial.png'});
await browser.close();
