import { memo } from 'react';
import { convertLatexToMarkup } from 'mathlive';
import 'mathlive/fonts.css';
import 'mathlive/static.css';

// Shared with the pure-maths workspace; HTML is generated by MathLive.
export const StaticMath = memo(function StaticMath({ value }: { value: string }) {
  return <span className="static-math" dangerouslySetInnerHTML={{ __html: convertLatexToMarkup(value) }} />;
});
